### ISSUE TITLE
neuer APIKey

### ISSUE THREAD

**Issue by hirnwunde** [xepheris/artifactpower#1]
Hey,

Du solltest Deinen APIKey erneuern.
Auch wenn Du ihn in den aktuellen Quellen entfernt hast, ist er immernoch in der Historie der API.php vorhanden.
https://github.com/xepheris/artifactpower/blob/38924629ae6bc97c5367bfb9e812b516e7f54a92/modules/api.php

**Comment by xepheris** [comment]
Ja, habe ich seitdem bereits getan, danke dennoch. :)
